"""'add_follow_relation'

Revision ID: 088efea2e353
Revises: bb316df81824
Create Date: 2018-11-03 11:40:16.356535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088efea2e353'
down_revision = 'bb316df81824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.String(length=100), nullable=False),
    sa.Column('followed_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['front_user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['front_user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
