"""'add_front_user'

Revision ID: 65721f804708
Revises: 2a05ae357014
Create Date: 2018-10-23 15:37:19.133643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65721f804708'
down_revision = '2a05ae357014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('realname', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'SECRET', 'UNKNOW', name='genderenum'), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telephone'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('telephone', table_name='frontuser')
    op.drop_index('username', table_name='frontuser')
    op.drop_table('frontuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frontuser',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('_password', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('realname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('signature', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('gender', mysql.ENUM('MALE', 'FEMALE', 'SECRET', 'UNKNOW'), nullable=True),
    sa.Column('join_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'frontuser', ['username'], unique=True)
    op.create_index('telephone', 'frontuser', ['telephone'], unique=True)
    op.drop_table('front_user')
    # ### end Alembic commands ###
