"""'add_board_model'

Revision ID: 692ff9e512a2
Revises: c2f8357db0b2
Create Date: 2018-10-27 12:15:41.029034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692ff9e512a2'
down_revision = 'c2f8357db0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
