"""'updata_banner_model'

Revision ID: b5e4f7a1eca3
Revises: 9ba084c343ea
Create Date: 2018-10-26 15:07:22.951077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e4f7a1eca3'
down_revision = '9ba084c343ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('link_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'link_url')
    # ### end Alembic commands ###
