"""'add_follow_timestamp'

Revision ID: ed17eb41b9cf
Revises: 088efea2e353
Create Date: 2018-11-03 11:54:24.409217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed17eb41b9cf'
down_revision = '088efea2e353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow', 'timestamp')
    # ### end Alembic commands ###
